name: Test Savills WIF

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/905155754460/locations/global/workloadIdentityPools/third-party-data-providers/providers/third-party-oidc'
          service_account: 'homesearch-data-provider@savills-warehouse.iam.gserviceaccount.com'

      - name: Upload test file
        run: |
          echo "Test from GitHub - $(date)" > test.txt
          gcloud storage cp test.txt gs://homesearch-raw/test/github-test.txt
          echo "✅ Upload successful!"
          
      - name: Verify upload
        run: |
          gcloud storage cat gs://homesearch-raw/test/github-test.txt
